version: '2'

services:



 db:
  image: mysql:8.0
  command: --default-authentication-plugin=mysql_native_password
  environment:
   MYSQL_ROOT_PASSWORD: R!OT
   MYSQL_DATABASE: INFO801
   MYSQL_USER: user
   MYSQL_PASSWORD: R!OT
  volumes:
   - ./SQL:/var/lib/mysql
  ports:
   - 3306:3306
  expose:
   - 3306/tcp
   - 3306/udp

 adminer:
  image: adminer:latest
  environment:
   PMA_ARBITRARY: 1
   PMA_HOST: db
   UPLOAD_LIMIT: 20M
  ports:
   - 8080:80
  expose:
    - 80/tcp
    - 80/udp
